apiVersion: v1
kind: Namespace
metadata:
  name: devsecops-app
  labels:
    name: devsecops-app
    environment: dev
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted